// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeiXinAPI.Data;

namespace WeiXinAPI.Migrations
{
    [DbContext(typeof(WinXinApiDbContext))]
    [Migration("20200227070550_updateSeed")]
    partial class updateSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("WeiXinAPI.Enitities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmedPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurdPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("WeiXinAPI.Enitities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmedPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurdPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52e9ee28-dae3-4977-b491-c1ee88014e56"),
                            ConfirmedPopulation = 513,
                            CurdPopulation = 16,
                            DeadPopulation = 0,
                            Name = "哈尔滨市",
                            ProvinceId = new Guid("db0185a5-48af-415f-b73f-46abc3fdc6ae"),
                            TotalPopulation = 10000
                        },
                        new
                        {
                            Id = new Guid("52e9ee88-dae3-4977-b491-c2ee88054e56"),
                            ConfirmedPopulation = 513,
                            CurdPopulation = 16,
                            DeadPopulation = 0,
                            Name = "上海市",
                            ProvinceId = new Guid("db0185a5-48af-415f-b73f-46abc3fdc6af"),
                            TotalPopulation = 10000
                        },
                        new
                        {
                            Id = new Guid("52e9ee88-dae3-5977-b491-c2ee88044e56"),
                            ConfirmedPopulation = 83,
                            CurdPopulation = 25,
                            DeadPopulation = 0,
                            Name = "南京市",
                            ProvinceId = new Guid("52e9ee88-dae3-4977-b491-c2ee88044e46"),
                            TotalPopulation = 10000
                        },
                        new
                        {
                            Id = new Guid("52e9ee88-dae3-4917-b491-c2ee88144e56"),
                            ConfirmedPopulation = 73,
                            CurdPopulation = 26,
                            DeadPopulation = 0,
                            Name = "苏州市",
                            ProvinceId = new Guid("52e9ee88-dae3-4977-b491-c2ee88044e46"),
                            TotalPopulation = 20000
                        },
                        new
                        {
                            Id = new Guid("52e9ea88-dae3-4977-b491-c2ee78144e56"),
                            ConfirmedPopulation = 53,
                            CurdPopulation = 46,
                            DeadPopulation = 0,
                            Name = "镇江市",
                            ProvinceId = new Guid("52e9ee88-dae3-4977-b491-c2ee88044e46"),
                            TotalPopulation = 30000
                        });
                });

            modelBuilder.Entity("WeiXinAPI.Enitities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmedPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurdPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("ProvCapital")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52e9ee88-dae3-4977-b491-c2ee88044e46"),
                            ConfirmedPopulation = 632,
                            CurdPopulation = 365,
                            DeadPopulation = 0,
                            Name = "江苏省",
                            ProvCapital = "南京市",
                            TotalPopulation = 10000000
                        },
                        new
                        {
                            Id = new Guid("db0185a5-48af-415f-b73f-46abc3fdc6af"),
                            ConfirmedPopulation = 536,
                            CurdPopulation = 265,
                            DeadPopulation = 2,
                            Name = "上海市",
                            ProvCapital = "上海市",
                            TotalPopulation = 20000000
                        },
                        new
                        {
                            Id = new Guid("db0185a5-48af-415f-b73f-46abc3fdc6ae"),
                            ConfirmedPopulation = 536,
                            CurdPopulation = 265,
                            DeadPopulation = 2,
                            Name = "黑龙江",
                            ProvCapital = "哈尔滨市",
                            TotalPopulation = 20000000
                        });
                });

            modelBuilder.Entity("WeiXinAPI.Enitities.Area", b =>
                {
                    b.HasOne("WeiXinAPI.Enitities.City", null)
                        .WithMany("Areas")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("WeiXinAPI.Enitities.City", b =>
                {
                    b.HasOne("WeiXinAPI.Enitities.Province", "province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
